export type WcagLevel = 'A' | 'AA' | 'AAA';

export interface WcagCriterionCondition {
  descripcion: string;
  selectores: string[];
}

export interface WcagCriterion {
  id: string;
  nombre: string;
  nivel: WcagLevel;
  condicion: WcagCriterionCondition | null;
}

export const wcagCriteria: WcagCriterion[] = [
  { id: '1.1.1', nombre: 'Contenido no textual', nivel: 'A', condicion: { descripcion: 'La página tiene imágenes u otro contenido no textual', selectores: ['img', 'svg:not([aria-hidden="true"])', '[role="img"]', 'canvas', 'input[type="image"]'] } },
  { id: '1.2.1', nombre: 'Solo audio o solo video pregrabado', nivel: 'A', condicion: { descripcion: 'La página tiene video o audio sin pista equivalente', selectores: ['video', 'audio'] } },
  { id: '1.2.2', nombre: 'Subtítulos pregrabado', nivel: 'A', condicion: { descripcion: 'La página tiene video con audio o audio', selectores: ['video', 'audio'] } },
  { id: '1.2.3', nombre: 'Audiodescripción o alternativa', nivel: 'A', condicion: { descripcion: 'La página tiene video con contenido visual significativo', selectores: ['video'] } },
  { id: '1.2.4', nombre: 'Subtítulos en vivo', nivel: 'AA', condicion: { descripcion: 'La página tiene video o audio en vivo', selectores: ['video[src*="m3u8"]', 'audio[src*="m3u8"]', 'video[src*="live"]', 'audio[src*="live"]'] } },
  { id: '1.2.5', nombre: 'Audiodescripción pregrabado', nivel: 'AA', condicion: { descripcion: 'La página tiene video con contenido visual significativo', selectores: ['video'] } },
  { id: '1.2.6', nombre: 'Lengua de señas', nivel: 'AAA', condicion: { descripcion: 'La página tiene audio o video con audio pregrabado', selectores: ['audio', 'video'] } },
  { id: '1.2.7', nombre: 'Audiodescripcion extendida', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene video', selectores: ['video'] } },
  { id: '1.2.8', nombre: 'Alternativa multimedia', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene video o audio', selectores: ['video', 'audio'] } },
  { id: '1.2.9', nombre: 'Solo audio en vivo', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene audio en vivo', selectores: ['audio[src*="m3u8"]', 'audio[src*="live"]'] } },
  { id: '1.3.1', nombre: 'Información y relaciones', nivel: 'A', condicion: null },
  { id: '1.3.2', nombre: 'Secuencia significativa', nivel: 'A', condicion: null },
  { id: '1.3.3', nombre: 'Características sensoriales', nivel: 'A', condicion: { descripcion: 'La página tiene instrucciones basadas en forma, color, posición o sonido', selectores: ['body'] } },
  { id: '1.3.4', nombre: 'Orientacion', nivel: 'AA', condicion: null },
  { id: '1.3.5', nombre: 'Identificar propósito de entrada', nivel: 'AA', condicion: { descripcion: 'La página tiene controles de entrada', selectores: ['input', 'select', 'textarea'] } },
  { id: '1.3.6', nombre: 'Identificar proposito', nivel: 'AAA', condicion: null },
  { id: '1.4.1', nombre: 'Uso del color', nivel: 'A', condicion: null },
  { id: '1.4.2', nombre: 'Control de audio', nivel: 'A', condicion: { descripcion: 'La página tiene audio que se reproduce automáticamente', selectores: ['audio[autoplay]', 'video[autoplay]'] } },
  { id: '1.4.3', nombre: 'Contraste mínimo texto', nivel: 'AA', condicion: null },
  { id: '1.4.4', nombre: 'Cambio de tamaño del texto', nivel: 'AA', condicion: null },
  { id: '1.4.5', nombre: 'Imágenes de texto', nivel: 'AA', condicion: { descripcion: 'La página tiene imágenes que pueden contener texto', selectores: ['img', 'svg'] } },
  { id: '1.4.6', nombre: 'Contraste mejorado', nivel: 'AAA', condicion: null },
  { id: '1.4.7', nombre: 'Sonido de fondo bajo o nulo', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene audio pregrabado con voz', selectores: ['audio', 'video'] } },
  { id: '1.4.8', nombre: 'Presentación visual', nivel: 'AAA', condicion: { descripcion: 'La página tiene bloques de texto', selectores: ['p', 'article', 'section', 'main'] } },
  { id: '1.4.9', nombre: 'Imágenes de texto sin excepción', nivel: 'AAA', condicion: { descripcion: 'La página tiene imágenes con texto', selectores: ['img', 'svg'] } },
  { id: '1.4.10', nombre: 'Reflow', nivel: 'AA', condicion: null },
  { id: '1.4.11', nombre: 'Contraste de componentes no textuales', nivel: 'AA', condicion: { descripcion: 'La página tiene controles, iconos funcionales o gráficos', selectores: ['button', 'input', 'select', 'textarea', '[role="button"]', 'svg:not([aria-hidden="true"])', 'canvas'] } },
  { id: '1.4.12', nombre: 'Espaciado de texto', nivel: 'AA', condicion: null },
  { id: '1.4.13', nombre: 'Contenido en hover o focus', nivel: 'AA', condicion: { descripcion: 'La página tiene tooltips, dropdowns o contenido activado por hover/focus', selectores: ['[role="tooltip"]', '.tooltip', '.dropdown', '[aria-haspopup]'] } },
  { id: '2.1.1', nombre: 'Teclado', nivel: 'A', condicion: null },
  { id: '2.1.2', nombre: 'Sin trampa de teclado', nivel: 'A', condicion: null },
  { id: '2.1.3', nombre: 'Teclado sin excepcion', nivel: 'AAA', condicion: null },
  { id: '2.1.4', nombre: 'Atajos de teclado de un solo carácter', nivel: 'A', condicion: { descripcion: 'La página implementa atajos de teclado personalizados', selectores: ['[accesskey]'] } },
  { id: '2.2.1', nombre: 'Tiempo ajustable', nivel: 'A', condicion: { descripcion: 'La pagina tiene limites de tiempo', selectores: ['meta[http-equiv="refresh"]', '[data-timeout]', '[data-timer]', '.timer', '.countdown'] } },
  { id: '2.2.2', nombre: 'Pausar detener ocultar', nivel: 'A', condicion: { descripcion: 'La pagina tiene contenido en movimiento automatico', selectores: ['marquee', '.carousel', '.slider', '[data-autoplay]'] } },
  { id: '2.2.3', nombre: 'Sin tiempo', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene limites de tiempo', selectores: ['meta[http-equiv="refresh"]', '[data-timeout]', '[data-timer]', '.timer', '.countdown'] } },
  { id: '2.2.4', nombre: 'Interrupciones', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene actualizaciones automaticas de contenido', selectores: ['[aria-live]', '[role="alert"]', '[role="status"]'] } },
  { id: '2.2.5', nombre: 'Re-autenticacion', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene sesion autenticada con expiracion', selectores: ['input[type="password"]', '[data-session]'] } },
  { id: '2.2.6', nombre: 'Tiempos de espera', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene datos del usuario que pueden perderse por inactividad', selectores: ['form', '[data-timeout]', '[data-session]'] } },
  { id: '2.3.1', nombre: 'Tres destellos o por debajo del umbral', nivel: 'A', condicion: { descripcion: 'La pagina tiene contenido que parpadea o destella', selectores: ['blink', '[data-flash]', '.flash', '.blink'] } },
  { id: '2.3.2', nombre: 'Tres destellos', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene contenido que parpadea', selectores: ['blink', '[data-flash]', '.flash', '.blink'] } },
  { id: '2.3.3', nombre: 'Animacion desde interacciones', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene animaciones CSS o JS activadas por interaccion', selectores: ['body'] } },
  { id: '2.4.1', nombre: 'Evitar bloques', nivel: 'A', condicion: null },
  { id: '2.4.2', nombre: 'Titulado de paginas', nivel: 'A', condicion: null },
  { id: '2.4.3', nombre: 'Orden del foco', nivel: 'A', condicion: null },
  { id: '2.4.4', nombre: 'Proposito de los enlaces en contexto', nivel: 'A', condicion: { descripcion: 'La pagina tiene enlaces', selectores: ['a[href]'] } },
  { id: '2.4.5', nombre: 'Multiples vias', nivel: 'AA', condicion: { descripcion: 'La pagina es parte de un sitio con multiples paginas', selectores: ['nav a[href]', '[aria-label*="breadcrumb" i]', '.breadcrumb', 'a[href*="sitemap"]'] } },
  { id: '2.4.6', nombre: 'Encabezados y etiquetas', nivel: 'AA', condicion: { descripcion: 'La pagina tiene encabezados o formularios con labels', selectores: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'label', 'input', 'select', 'textarea'] } },
  { id: '2.4.7', nombre: 'Foco visible', nivel: 'AA', condicion: null },
  { id: '2.4.8', nombre: 'Ubicacion', nivel: 'AAA', condicion: { descripcion: 'La pagina es parte de un sitio con multiples paginas', selectores: ['nav a[href]', '[aria-label*="breadcrumb" i]', '.breadcrumb'] } },
  { id: '2.4.9', nombre: 'Proposito del enlace solo', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene enlaces', selectores: ['a[href]'] } },
  { id: '2.4.10', nombre: 'Encabezados de seccion', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene contenido organizado en secciones', selectores: ['section', 'article', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'] } },
  { id: '2.4.11', nombre: 'Foco no oculto', nivel: 'AA', condicion: null },
  { id: '2.4.12', nombre: 'Foco no oculto mejorado', nivel: 'AAA', condicion: null },
  { id: '2.4.13', nombre: 'Apariencia del foco', nivel: 'AAA', condicion: null },
  { id: '2.5.1', nombre: 'Gestos del puntero', nivel: 'A', condicion: { descripcion: 'La pagina tiene funcionalidad con gestos multitactiles o trayectoria', selectores: ['[data-gesture]', '[data-swipe]', 'canvas'] } },
  { id: '2.5.2', nombre: 'Cancelacion del puntero', nivel: 'A', condicion: { descripcion: 'La pagina tiene funcionalidad activada con clic o toque', selectores: ['button', 'a[href]', 'input', 'select', 'textarea', '[role="button"]'] } },
  { id: '2.5.3', nombre: 'Etiqueta en nombre accesible', nivel: 'A', condicion: { descripcion: 'La pagina tiene componentes con etiqueta de texto visible', selectores: ['button', 'a[href]', 'label', '[aria-label]', '[aria-labelledby]'] } },
  { id: '2.5.4', nombre: 'Actuacion mediante movimiento', nivel: 'A', condicion: { descripcion: 'La pagina tiene funcionalidad que responde a movimiento del dispositivo', selectores: ['[data-motion]', '[data-orientation]'] } },
  { id: '2.5.5', nombre: 'Tamano del objetivo', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene elementos interactivos clickeables', selectores: ['button', 'a[href]', 'input', 'select', 'textarea', '[role="button"]'] } },
  { id: '2.5.6', nombre: 'Mecanismos de entrada concurrentes', nivel: 'AAA', condicion: null },
  { id: '2.5.7', nombre: 'Movimientos de arrastre', nivel: 'AA', condicion: { descripcion: 'La pagina tiene drag and drop', selectores: ['[draggable="true"]'] } },
  { id: '2.5.8', nombre: 'Tamano del objetivo minimo', nivel: 'AA', condicion: { descripcion: 'La pagina tiene elementos interactivos clickeables', selectores: ['button', 'a[href]', 'input', 'select', 'textarea', '[role="button"]'] } },
  { id: '3.1.1', nombre: 'Idioma de la pagina', nivel: 'A', condicion: null },
  { id: '3.1.2', nombre: 'Idioma de las partes', nivel: 'AA', condicion: { descripcion: 'La pagina tiene texto en mas de un idioma', selectores: ['[lang]'] } },
  { id: '3.1.3', nombre: 'Palabras inusuales', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene terminos tecnicos o jerga', selectores: ['abbr', 'dfn'] } },
  { id: '3.1.4', nombre: 'Abreviaturas', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene abreviaturas o siglas', selectores: ['abbr'] } },
  { id: '3.1.5', nombre: 'Nivel de lectura', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene contenido de texto extenso', selectores: ['article', 'main', 'p'] } },
  { id: '3.1.6', nombre: 'Pronunciacion', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene palabras ambiguas sin contexto de pronunciacion', selectores: ['ruby', 'abbr'] } },
  { id: '3.2.1', nombre: 'Al recibir el foco', nivel: 'A', condicion: null },
  { id: '3.2.2', nombre: 'Al recibir entradas', nivel: 'A', condicion: { descripcion: 'La pagina tiene controles que cambian valor', selectores: ['select', 'input[type="checkbox"]', 'input[type="radio"]', 'input', 'textarea'] } },
  { id: '3.2.3', nombre: 'Navegacion coherente', nivel: 'AA', condicion: { descripcion: 'La pagina es parte de un sitio con multiples paginas', selectores: ['nav a[href]', '[aria-label*="breadcrumb" i]', '.breadcrumb'] } },
  { id: '3.2.4', nombre: 'Identificacion coherente', nivel: 'AA', condicion: { descripcion: 'La pagina es parte de un sitio con multiples paginas', selectores: ['nav a[href]', '[aria-label*="breadcrumb" i]', '.breadcrumb'] } },
  { id: '3.2.5', nombre: 'Cambio a peticion', nivel: 'AAA', condicion: null },
  { id: '3.2.6', nombre: 'Ayuda consistente', nivel: 'A', condicion: { descripcion: 'La pagina tiene mecanismo de ayuda', selectores: ['a[href*="ayuda"]', 'a[href*="help"]', 'a[href*="contacto"]', '[aria-label*="ayuda" i]', '[aria-label*="help" i]'] } },
  { id: '3.3.1', nombre: 'Identificacion de errores', nivel: 'A', condicion: { descripcion: 'La pagina tiene formularios con validacion', selectores: ['form', 'input[required]', 'select[required]', 'textarea[required]', '[aria-invalid]'] } },
  { id: '3.3.2', nombre: 'Etiquetas o instrucciones', nivel: 'A', condicion: { descripcion: 'La pagina tiene formularios con inputs', selectores: ['form', 'input', 'select', 'textarea'] } },
  { id: '3.3.3', nombre: 'Sugerencia tras error', nivel: 'AA', condicion: { descripcion: 'La pagina tiene formularios con validacion', selectores: ['form', 'input[required]', 'select[required]', 'textarea[required]', '[aria-invalid]'] } },
  { id: '3.3.4', nombre: 'Prevencion de errores legales financieros', nivel: 'AA', condicion: { descripcion: 'La pagina tiene transacciones legales, financieras o datos privados', selectores: ['form', 'input[type="password"]', 'input[name*="card" i]', 'input[name*="dni" i]'] } },
  { id: '3.3.5', nombre: 'Ayuda contextual', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene formularios', selectores: ['form', 'input', 'select', 'textarea'] } },
  { id: '3.3.6', nombre: 'Prevencion de errores', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene formularios con envio de datos', selectores: ['form', 'button[type="submit"]', 'input[type="submit"]'] } },
  { id: '3.3.7', nombre: 'Entrada redundante', nivel: 'A', condicion: { descripcion: 'La pagina tiene procesos multipaso que piden informacion', selectores: ['[data-step]', '.wizard', '.step', '.stepper'] } },
  { id: '3.3.8', nombre: 'Autenticacion accesible', nivel: 'AA', condicion: { descripcion: 'La pagina tiene login, captcha o autenticacion', selectores: ['input[type="password"]', 'iframe[src*="recaptcha"]', 'iframe[src*="captcha"]', '.g-recaptcha', '[data-sitekey]'] } },
  { id: '3.3.9', nombre: 'Autenticacion accesible mejorada', nivel: 'AAA', condicion: { descripcion: 'La pagina tiene login, captcha o autenticacion', selectores: ['input[type="password"]', 'iframe[src*="recaptcha"]', 'iframe[src*="captcha"]', '.g-recaptcha', '[data-sitekey]'] } },
  { id: '4.1.2', nombre: 'Nombre funcion valor', nivel: 'A', condicion: null },
  { id: '4.1.3', nombre: 'Mensajes de estado', nivel: 'AA', condicion: { descripcion: 'La pagina tiene mensajes de estado dinamicos', selectores: ['[role="alert"]', '[role="status"]', '[aria-live]'] } },
];

export const WCAG_CRITERIA_COUNT = 86;
